import { JsonStorageService } from './json-storage.service';
import {
  CompanyDto,
  CompanyType,
  CompanySize,
  CompanyStage,
  CompanyRelationship,
} from '../shared/dtos/company.dto';
import {
  ProductDto,
  ProductCategory,
  ProductSubcategory,
  Platform,
  TargetAudience,
  MonetizationModel,
  ProductRelationship,
  ProductStatus,
} from '../shared/dtos/product.dto';
import { v4 as uuidv4 } from 'uuid';

const now = new Date();

/**
 * Seed sample companies and products for the Product Intelligence Platform
 */
export function seedProductDatabase(storage: JsonStorageService): void {
  console.log('🌱 Seeding Product Intelligence database...');

  // ==========================================
  // COMPANIES
  // ==========================================

  const companies: Partial<CompanyDto>[] = [
    // Online Training
    {
      id: uuidv4(),
      name: 'Coursera',
      slug: 'coursera',
      description:
        'Online learning platform partnering with universities and companies to offer courses, certificates, and degrees.',
      tagline: 'Learn without limits',
      companyType: CompanyType.EdTech,
      relationship: CompanyRelationship.Reference,
      size: CompanySize.Large,
      stage: CompanyStage.PubliclyTraded,
      foundedYear: 2012,
      contact: {
        website: 'https://coursera.org',
        linkedIn: 'https://linkedin.com/company/coursera',
        twitter: 'https://twitter.com/coursera',
        headquarters: 'Mountain View, CA',
        country: 'USA',
      },
      funding: {
        totalFunding: 464000000,
        isPublic: true,
        stockSymbol: 'COUR',
        employees: 1500,
        annualRevenue: 500000000,
      },
      metrics: {
        totalUsers: 136000000,
        monthlyActiveUsers: 20000000,
      },
      strengths: [
        'University partnerships',
        'Degree programs',
        'Enterprise sales',
      ],
      weaknesses: ['High course prices', 'Completion rates'],
      targetMarkets: [
        'Higher Education',
        'Professional Development',
        'Enterprise Training',
      ],
      threatLevel: 'High',
      tags: ['edtech', 'online-learning', 'mooc', 'certificates'],
    },
    {
      id: uuidv4(),
      name: 'Udemy',
      slug: 'udemy',
      description:
        'Marketplace for online learning with 200,000+ courses taught by expert instructors.',
      tagline: 'Learn anything, on your schedule',
      companyType: CompanyType.EdTech,
      relationship: CompanyRelationship.Competitor,
      size: CompanySize.Large,
      stage: CompanyStage.PubliclyTraded,
      foundedYear: 2010,
      contact: {
        website: 'https://udemy.com',
        headquarters: 'San Francisco, CA',
        country: 'USA',
      },
      funding: {
        totalFunding: 300000000,
        isPublic: true,
        stockSymbol: 'UDMY',
        employees: 1000,
        annualRevenue: 600000000,
      },
      metrics: {
        totalUsers: 67000000,
        monthlyActiveUsers: 15000000,
      },
      strengths: ['Marketplace model', 'Price flexibility', 'Course variety'],
      weaknesses: ['Quality inconsistency', 'No accreditation'],
      threatLevel: 'High',
      tags: ['edtech', 'marketplace', 'online-courses'],
    },
    // AI Companies
    {
      id: uuidv4(),
      name: 'Anthropic',
      slug: 'anthropic',
      description:
        'AI safety company building reliable, interpretable AI systems.',
      tagline: 'AI research company focused on safety',
      companyType: CompanyType.AICompany,
      relationship: CompanyRelationship.Reference,
      size: CompanySize.Medium,
      stage: CompanyStage.SeriesC,
      foundedYear: 2021,
      contact: {
        website: 'https://anthropic.com',
        headquarters: 'San Francisco, CA',
        country: 'USA',
      },
      funding: {
        totalFunding: 7300000000,
        lastRoundAmount: 4000000000,
        isPublic: false,
        employees: 500,
        valuation: 18000000000,
      },
      strengths: ['Safety focus', 'Constitutional AI', 'Enterprise adoption'],
      targetMarkets: ['Enterprise AI', 'Developer Tools', 'Consumer AI'],
      threatLevel: 'Low',
      tags: ['ai', 'llm', 'safety', 'claude'],
    },
    {
      id: uuidv4(),
      name: 'OpenAI',
      slug: 'openai',
      description:
        'AI research and deployment company with mission to ensure AGI benefits humanity.',
      tagline: 'Creating safe AGI',
      companyType: CompanyType.AICompany,
      relationship: CompanyRelationship.Reference,
      size: CompanySize.Medium,
      stage: CompanyStage.SeriesC,
      foundedYear: 2015,
      contact: {
        website: 'https://openai.com',
        headquarters: 'San Francisco, CA',
        country: 'USA',
      },
      funding: {
        totalFunding: 11300000000,
        isPublic: false,
        employees: 800,
        valuation: 86000000000,
        annualRevenue: 2000000000,
      },
      metrics: {
        totalUsers: 200000000,
        monthlyActiveUsers: 100000000,
      },
      strengths: ['Market leader', 'GPT models', 'Microsoft partnership'],
      weaknesses: ['Safety concerns', 'Competition increasing'],
      threatLevel: 'Low',
      tags: ['ai', 'llm', 'chatgpt', 'gpt'],
    },
    // Productivity
    {
      id: uuidv4(),
      name: 'Notion',
      slug: 'notion',
      description:
        'All-in-one workspace for notes, docs, wikis, and project management.',
      tagline: 'One tool for your whole team',
      companyType: CompanyType.Productivity,
      relationship: CompanyRelationship.Competitor,
      size: CompanySize.Medium,
      stage: CompanyStage.SeriesC,
      foundedYear: 2013,
      contact: {
        website: 'https://notion.so',
        headquarters: 'San Francisco, CA',
        country: 'USA',
      },
      funding: {
        totalFunding: 343000000,
        isPublic: false,
        employees: 500,
        valuation: 10000000000,
      },
      metrics: {
        totalUsers: 30000000,
        monthlyActiveUsers: 10000000,
      },
      strengths: ['Flexibility', 'Template ecosystem', 'AI integration'],
      weaknesses: ['Learning curve', 'Mobile experience'],
      threatLevel: 'Medium',
      tags: ['productivity', 'notes', 'wiki', 'project-management'],
    },
    {
      id: uuidv4(),
      name: 'Obsidian',
      slug: 'obsidian',
      description:
        'Knowledge base that works on local Markdown files with powerful linking.',
      tagline: 'A second brain, for you, forever',
      companyType: CompanyType.Productivity,
      relationship: CompanyRelationship.Complementary,
      size: CompanySize.Small,
      stage: CompanyStage.Bootstrapped,
      foundedYear: 2020,
      contact: {
        website: 'https://obsidian.md',
        country: 'Canada',
      },
      funding: {
        totalFunding: 0,
        isPublic: false,
        employees: 20,
      },
      metrics: {
        totalUsers: 1000000,
      },
      strengths: ['Local-first', 'Plugin ecosystem', 'Privacy'],
      weaknesses: ['No real-time collab', 'Developer-focused'],
      threatLevel: 'Low',
      tags: ['productivity', 'notes', 'markdown', 'pkm'],
    },
    // Family Tech
    {
      id: uuidv4(),
      name: 'Life360',
      slug: 'life360',
      description:
        'Family safety and location sharing platform with 50M active families.',
      tagline: 'Everyday family safety',
      companyType: CompanyType.FamilyTech,
      relationship: CompanyRelationship.Competitor,
      size: CompanySize.Medium,
      stage: CompanyStage.PubliclyTraded,
      foundedYear: 2008,
      contact: {
        website: 'https://life360.com',
        headquarters: 'San Francisco, CA',
        country: 'USA',
      },
      funding: {
        totalFunding: 160000000,
        isPublic: true,
        stockSymbol: 'LIF',
        employees: 500,
        annualRevenue: 300000000,
      },
      metrics: {
        totalUsers: 50000000,
        monthlyActiveUsers: 35000000,
      },
      strengths: ['Market leader', 'Location accuracy', 'Teen safety'],
      weaknesses: ['Privacy concerns', 'Battery drain'],
      threatLevel: 'High',
      tags: ['family', 'location', 'safety', 'mobile'],
    },
    {
      id: uuidv4(),
      name: 'Cozi',
      slug: 'cozi',
      description:
        'Family organizer app for shared calendars, lists, and meal planning.',
      tagline: 'The #1 organizing app for families',
      companyType: CompanyType.FamilyTech,
      relationship: CompanyRelationship.Reference,
      size: CompanySize.Small,
      stage: CompanyStage.Acquired,
      foundedYear: 2005,
      contact: {
        website: 'https://cozi.com',
        country: 'USA',
      },
      funding: {
        totalFunding: 25000000,
        isPublic: false,
        employees: 50,
      },
      metrics: {
        totalUsers: 25000000,
      },
      strengths: ['Simple UX', 'Shared calendars', 'Recipe integration'],
      weaknesses: ['Dated design', 'Limited features'],
      threatLevel: 'Low',
      tags: ['family', 'calendar', 'organization'],
    },
  ];

  // ==========================================
  // PRODUCTS
  // ==========================================

  const products: Partial<ProductDto>[] = [
    // ==========================================
    // OUR GAMES (3)
    // ==========================================
    {
      id: uuidv4(),
      name: 'Dragon Legends',
      slug: 'dragon-legends',
      tagline: 'Collect. Breed. Conquer.',
      description:
        'Epic dragon collection game with breeding, battling, and trading. Collect 500+ unique dragons across elemental types.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Simulation,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Children, TargetAudience.Teens],
      relationship: ProductRelationship.OurProduct,
      status: ProductStatus.InDevelopment,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasAchievements: true,
        hasRewards: true,
        hasProgress: true,
        hasMicroTransactions: true,
        hasTrading: true,
        hasCollection: true,
        hasBreeding: true,
        hasBattles: true,
        hasDailyRewards: true,
        hasEvents: true,
        hasGuilds: true,
      } as any,
      metrics: {
        totalUsers: 0,
        monthlyActiveUsers: 0,
        averageRating: 0,
        projectedMonthlyRevenue: 50000,
        developmentProgress: 35,
      } as any,
      strengths: [
        'Unique dragon theme differentiates from pet simulators',
        'Breeding system adds depth beyond collection',
        'Elemental combat creates strategic gameplay',
        'Epic visual style appeals to older kids/teens',
        'Trading economy for dragon marketplace',
      ],
      weaknesses: [
        'More complex than typical simulators',
        'Needs strong balancing for combat',
        'Higher art asset requirements',
      ],
      uniqueSellingPoints: [
        'Dragon breeding with genetics system',
        'Elemental rock-paper-scissors combat',
        'Dragon evolution chains',
        'Aerial dragon racing',
        'Guild dragon wars',
      ],
      lessonsLearned: [
        'Studying Pet Simulator X egg mechanics',
        'Blox Fruits combat as reference',
        'Adopt Me aging for inspiration',
      ],
      priorityScore: 90,
      recommendedForStudy: false,
      tags: [
        'roblox',
        'game',
        'dragons',
        'collection',
        'breeding',
        'our-game',
        'development',
      ],
    },
    {
      id: uuidv4(),
      name: 'Lucky Fish Legends',
      slug: 'lucky-fish-legends',
      tagline: 'Cast your line, catch your fortune!',
      description:
        'Relaxing fishing simulator with rare fish collection, aquarium building, and underwater exploration.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Simulation,
      platforms: [Platform.Roblox],
      targetAudiences: [
        TargetAudience.Children,
        TargetAudience.Teens,
        TargetAudience.Adults,
      ],
      relationship: ProductRelationship.OurProduct,
      status: ProductStatus.InDevelopment,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasAchievements: true,
        hasRewards: true,
        hasProgress: true,
        hasMicroTransactions: true,
        hasTrading: true,
        hasCollection: true,
        hasAquarium: true,
        hasFishing: true,
        hasDailyRewards: true,
        hasEvents: true,
        hasSeasons: true,
      } as any,
      metrics: {
        totalUsers: 0,
        monthlyActiveUsers: 0,
        averageRating: 0,
        projectedMonthlyRevenue: 30000,
        developmentProgress: 20,
      } as any,
      strengths: [
        'Relaxing gameplay appeals to casual audience',
        'Lower barrier to entry than combat games',
        'Aquarium building = housing satisfaction',
        'Seasonal fish create event-driven play',
        'Underwater exploration adds adventure',
      ],
      weaknesses: [
        'Fishing niche smaller than pet collecting',
        'Less viral potential than competitive games',
        'Need variety to prevent repetition',
      ],
      uniqueSellingPoints: [
        'Custom aquarium building and decoration',
        'Rare legendary fish with special abilities',
        'Underwater diving exploration',
        'Fish fusion for unique hybrids',
        'Fishing tournaments with prizes',
      ],
      lessonsLearned: [
        'Cat Game proved fishing can work',
        'Aquarium Tycoon retention mechanics',
        'Simple core loop is key',
      ],
      priorityScore: 75,
      recommendedForStudy: false,
      tags: [
        'roblox',
        'game',
        'fishing',
        'collection',
        'aquarium',
        'our-game',
        'development',
      ],
    },
    {
      id: uuidv4(),
      name: 'Family Quest',
      slug: 'family-quest',
      tagline: 'Adventures for the whole family!',
      description:
        'Cooperative family adventure game with quests, puzzles, and rewards that parents and kids complete together.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Casual,
      platforms: [Platform.Roblox],
      targetAudiences: [
        TargetAudience.Families,
        TargetAudience.Parents,
        TargetAudience.Children,
      ],
      relationship: ProductRelationship.OurProduct,
      status: ProductStatus.Concept,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      featureFlags: {
        hasMultiplayer: true,
        hasAchievements: true,
        hasRewards: true,
        hasProgress: true,
        hasMicroTransactions: true,
        hasQuests: true,
        hasPuzzles: true,
        hasFamilyFeatures: true,
        hasParentControls: true,
        hasDailyRewards: true,
      } as any,
      metrics: {
        totalUsers: 0,
        monthlyActiveUsers: 0,
        averageRating: 0,
        projectedMonthlyRevenue: 20000,
        developmentProgress: 5,
      } as any,
      strengths: [
        'Underserved family co-op niche on Roblox',
        'Parents want to play WITH kids safely',
        'Educational elements appeal to parents',
        'Lower competition than pet simulators',
        'Cross-generational appeal',
      ],
      weaknesses: [
        'Smaller addressable market',
        'Complex multiplayer coordination',
        'Parents less likely to spend',
      ],
      uniqueSellingPoints: [
        'Designed for parent-child co-op',
        'Age-appropriate content guaranteed',
        'Educational puzzle elements',
        'Family achievement system',
        'Safe chat and moderation',
      ],
      lessonsLearned: [
        'Brookhaven family roleplay success',
        'Parents underserved as players',
        'Safety is paramount for family games',
      ],
      priorityScore: 60,
      recommendedForStudy: false,
      tags: [
        'roblox',
        'game',
        'family',
        'coop',
        'adventure',
        'our-game',
        'concept',
      ],
    },

    // ==========================================
    // TOP VIRAL ROBLOX GAMES (Reference/Competitors)
    // ==========================================
    {
      id: uuidv4(),
      name: 'Fish It! 🐟',
      slug: 'fish-it',
      tagline: 'The viral fishing sensation',
      description:
        'Currently #1 viral game on Roblox. Simple tap-to-catch fishing with rare fish collection and leaderboards.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Simulation,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Children, TargetAudience.Teens],
      relationship: ProductRelationship.Inspiration,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      launchDate: new Date('2024-11-01'),
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasCollection: true,
        hasMicroTransactions: true,
        hasAchievements: true,
        hasDailyRewards: true,
      } as any,
      metrics: {
        totalUsers: 500000000,
        concurrentPlayers: 940000,
        monthlyActiveUsers: 50000000,
        dailyActiveUsers: 12000000,
        revenueMonthly: 1500000,
        revenueAnnual: 18000000,
        averageRating: 4.7,
        reviewCount: 350000,
        retentionDay1: 70,
        retentionDay7: 45,
        retentionDay30: 22,
      } as any,
      strengths: [
        'Extremely simple loop',
        'Viral TikTok clips',
        'Low dev complexity',
        'Fast session times',
        'Collection dopamine hits',
      ],
      uniqueSellingPoints: [
        'One-tap fishing',
        'Rare fish flex culture',
        'Real-time leaderboards',
        'Fish trading',
        'Daily challenges',
      ],
      priorityScore: 98,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'fishing', 'viral', 'simulator', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'Adopt Me!',
      slug: 'adopt-me',
      tagline: 'Virtual pet adoption and nurturing',
      description:
        'One of the most successful Roblox games ever. Pet collection, trading, housing, and social features.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Simulation,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Children, TargetAudience.Families],
      relationship: ProductRelationship.Competitor,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      launchDate: new Date('2017-07-14'),
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: false,
        hasCollection: true,
        hasTrading: true,
        hasMicroTransactions: true,
        hasHousing: true,
        hasDailyRewards: true,
        hasEvents: true,
        hasPets: true,
      } as any,
      metrics: {
        totalUsers: 3800000000,
        concurrentPlayers: 500000,
        monthlyActiveUsers: 100000000,
        dailyActiveUsers: 25000000,
        revenueMonthly: 3000000,
        revenueAnnual: 36000000,
        averageRating: 4.8,
        reviewCount: 2500000,
        retentionDay1: 65,
        retentionDay7: 38,
        retentionDay30: 18,
      } as any,
      strengths: [
        'Pet collection mastery',
        'Trading economy',
        'Event-driven updates',
        'Strong social features',
        'Family-friendly content',
      ],
      uniqueSellingPoints: [
        'Pet aging system',
        'House customization',
        'Trading with friends',
        'Neon/Mega neon pets',
        'Seasonal events',
      ],
      priorityScore: 95,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'pets', 'trading', 'social', 'competitor'],
    },
    {
      id: uuidv4(),
      name: 'Blox Fruits',
      slug: 'blox-fruits',
      tagline: 'Anime-inspired devil fruit powers',
      description:
        'One Piece inspired RPG with grinding, PvP combat, fruit powers, and raids. Massive teen audience.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.RPG,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Teens],
      relationship: ProductRelationship.Competitor,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      launchDate: new Date('2019-01-16'),
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasPvP: true,
        hasQuests: true,
        hasLevelSystem: true,
        hasMicroTransactions: true,
        hasTrading: true,
        hasBosses: true,
        hasGuilds: true,
      } as any,
      metrics: {
        totalUsers: 4500000000,
        concurrentPlayers: 600000,
        monthlyActiveUsers: 80000000,
        dailyActiveUsers: 18000000,
        revenueMonthly: 2500000,
        revenueAnnual: 30000000,
        averageRating: 4.6,
        reviewCount: 1800000,
        retentionDay1: 55,
        retentionDay7: 32,
        retentionDay30: 15,
      } as any,
      strengths: [
        'Deep grinding loop',
        'Anime IP appeal',
        'Regular content updates',
        'Strong PvP community',
        'Raid boss content',
      ],
      uniqueSellingPoints: [
        'Devil fruit powers',
        'Raid bosses',
        'Fruit trading',
        'Sea exploration',
        'Awakening system',
      ],
      priorityScore: 94,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'anime', 'rpg', 'combat', 'competitor'],
    },
    {
      id: uuidv4(),
      name: 'Brookhaven RP',
      slug: 'brookhaven-rp',
      tagline: 'The roleplay town simulation',
      description:
        'Open-world roleplay with houses, vehicles, and social interactions. Massive casual audience.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Simulation,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Children, TargetAudience.Teens],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      launchDate: new Date('2020-04-09'),
      featureFlags: {
        hasMultiplayer: true,
        hasHousing: true,
        hasVehicles: true,
        hasMicroTransactions: true,
        hasCustomization: true,
        hasEvents: true,
      } as any,
      metrics: {
        totalUsers: 3200000000,
        concurrentPlayers: 400000,
        monthlyActiveUsers: 60000000,
        dailyActiveUsers: 15000000,
        revenueMonthly: 2000000,
        revenueAnnual: 24000000,
        averageRating: 4.5,
        reviewCount: 1200000,
        retentionDay1: 50,
        retentionDay7: 28,
        retentionDay30: 12,
      } as any,
      strengths: [
        'Pure sandbox freedom',
        'No objectives = no pressure',
        'Family roleplay',
        'Consistent updates',
        'Low barrier to entry',
      ],
      uniqueSellingPoints: [
        'Open world town',
        'Premium houses',
        'Vehicle variety',
        'Roleplay flexibility',
        'Social sandbox',
      ],
      priorityScore: 90,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'roleplay', 'social', 'reference'],
    },
    {
      id: uuidv4(),
      name: "Sol's RNG",
      slug: 'sols-rng',
      tagline: 'Pure luck simulator',
      description:
        'Roll for rare auras with extreme rarity tiers. Zero skill barrier - pure gambling psychology.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Casual,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Teens],
      relationship: ProductRelationship.Inspiration,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      launchDate: new Date('2024-01-15'),
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasGacha: true,
        hasMicroTransactions: true,
        hasTrading: true,
        hasCollection: true,
      } as any,
      metrics: {
        totalUsers: 800000000,
        concurrentPlayers: 350000,
        monthlyActiveUsers: 30000000,
        dailyActiveUsers: 8000000,
        revenueMonthly: 800000,
        revenueAnnual: 9600000,
        averageRating: 4.4,
        reviewCount: 400000,
        retentionDay1: 62,
        retentionDay7: 40,
        retentionDay30: 20,
      } as any,
      strengths: [
        'Highest margin monetization',
        'Zero skill barrier',
        'Flex culture',
        'Addictive gambling loop',
        'Viral flex moments',
      ],
      uniqueSellingPoints: [
        'Pure RNG gameplay',
        'Visible auras as status',
        'Extreme rarities',
        'Luck boosts',
        'Biome bonuses',
      ],
      priorityScore: 92,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'rng', 'gacha', 'luck', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'Dress To Impress',
      slug: 'dress-to-impress',
      tagline: 'Competitive fashion game',
      description:
        'Timed fashion competition with player voting. Social validation loops and creator expression.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Casual,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Teens],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasCustomization: true,
        hasMicroTransactions: true,
      } as any,
      metrics: {
        totalUsers: 600000000,
        concurrentPlayers: 400000,
        monthlyActiveUsers: 25000000,
        averageRating: 4.6,
      } as any,
      strengths: ['Social validation', 'Creator expression', 'High retention'],
      uniqueSellingPoints: [
        'Theme-based rounds',
        'Player voting',
        'Runway walks',
      ],
      priorityScore: 88,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'fashion', 'social', 'voting', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'The Strongest Battlegrounds',
      slug: 'the-strongest-battlegrounds',
      tagline: 'Anime combat arena',
      description:
        'One Punch Man inspired combat game with character abilities and ranked PvP.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.ActionGame,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Teens],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      featureFlags: {
        hasMultiplayer: true,
        hasPvP: true,
        hasLeaderboards: true,
        hasMicroTransactions: true,
      } as any,
      metrics: {
        totalUsers: 300000000,
        concurrentPlayers: 200000,
        monthlyActiveUsers: 15000000,
        averageRating: 4.5,
      } as any,
      strengths: [
        'Skill-based combat',
        'Anime IP appeal',
        'Ranked matchmaking',
      ],
      uniqueSellingPoints: [
        'Character ultimates',
        'Competitive 1v1',
        'Anime moves',
      ],
      priorityScore: 85,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'anime', 'combat', 'pvp', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'RIVALS',
      slug: 'rivals',
      tagline: 'Competitive tactical FPS',
      description:
        'High-stakes competitive shooter with skill-based matchmaking and ranked play.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.ActionGame,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Teens],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      featureFlags: {
        hasMultiplayer: true,
        hasPvP: true,
        hasLeaderboards: true,
        hasRanked: true,
        hasMicroTransactions: true,
      } as any,
      metrics: {
        totalUsers: 200000000,
        concurrentPlayers: 250000,
        monthlyActiveUsers: 12000000,
        averageRating: 4.6,
      } as any,
      strengths: ['Esports potential', 'Skill-based gameplay', 'Premium skins'],
      uniqueSellingPoints: [
        'Ranked matchmaking',
        'Competitive modes',
        'Skin economy',
      ],
      priorityScore: 82,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'fps', 'competitive', 'esports', 'reference'],
    },

    // ==========================================
    // AI AGENTS & ASSISTANTS
    // ==========================================
    {
      id: uuidv4(),
      name: 'Claude',
      slug: 'claude',
      tagline: 'AI assistant by Anthropic',
      description:
        'Constitutional AI assistant focused on being helpful, harmless, and honest. Long context, coding, and analysis.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.Chatbot,
      platforms: [Platform.Web, Platform.API],
      targetAudiences: [
        TargetAudience.Developers,
        TargetAudience.Adults,
        TargetAudience.Enterprise,
      ],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 20,
      featureFlags: {
        hasUserAccounts: true,
        hasAPI: true,
        hasAIGeneration: true,
        hasAIAssistant: true,
        hasNaturalLanguage: true,
        hasFreeTier: true,
        hasSubscription: true,
        hasLongContext: true,
        hasCodeGeneration: true,
        hasArtifacts: true,
      } as any,
      metrics: {
        totalUsers: 10000000,
        monthlyActiveUsers: 5000000,
        averageRating: 4.8,
        contextWindow: 200000,
        apiCostPer1MTokens: 15,
      } as any,
      strengths: [
        'Constitutional AI ensures safe outputs',
        '200K token context window - industry leading',
        'Strong coding and analysis capabilities',
        'Artifacts feature for interactive content',
        'Enterprise-grade reliability',
      ],
      weaknesses: [
        'No real-time internet access',
        'Image generation limited',
        'Smaller ecosystem than ChatGPT',
      ],
      uniqueSellingPoints: [
        '200K context window',
        'Constitutional AI safety',
        'Artifacts for code/documents',
        'Claude 3.5 Sonnet performance',
        'Computer use capabilities',
      ],
      lessonsLearned: [
        'Safety focus builds enterprise trust',
        'Long context enables new use cases',
        'Artifacts create sticky usage',
      ],
      priorityScore: 95,
      recommendedForStudy: true,
      tags: ['ai', 'chatbot', 'llm', 'productivity', 'coding', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'ChatGPT',
      slug: 'chatgpt',
      tagline: 'Conversational AI by OpenAI',
      description:
        'AI chatbot powered by GPT-4 for conversation, writing, coding, and image generation.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.Chatbot,
      platforms: [Platform.Web, Platform.iOS, Platform.Android, Platform.API],
      targetAudiences: [TargetAudience.General, TargetAudience.Developers],
      relationship: ProductRelationship.Competitor,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 20,
      featureFlags: {
        hasUserAccounts: true,
        hasAPI: true,
        hasMobileApp: true,
        hasAIGeneration: true,
        hasAIAssistant: true,
        hasNaturalLanguage: true,
        hasImageGeneration: true,
        hasVoice: true,
        hasPlugins: true,
        hasGPTs: true,
      } as any,
      metrics: {
        totalUsers: 200000000,
        monthlyActiveUsers: 100000000,
        averageRating: 4.6,
        weeklyActiveUsers: 80000000,
        contextWindow: 128000,
        revenueAnnual: 2000000000,
      } as any,
      strengths: [
        'Market leader with massive user base',
        'GPT-4 performance benchmark',
        'Plugin/GPT ecosystem',
        'DALL-E image generation built-in',
        'Voice mode for conversations',
        'Microsoft partnership & distribution',
      ],
      weaknesses: [
        'Rate limits frustrate power users',
        'Hallucinations remain issue',
        'Privacy concerns from enterprise',
        'Increasing competition',
      ],
      uniqueSellingPoints: [
        'GPT Store with custom GPTs',
        'Multimodal (text, image, voice)',
        'Browser and file analysis',
        'Canvas for document editing',
      ],
      lessonsLearned: [
        'First mover advantage is powerful',
        'Consumer + API dual strategy works',
        'Plugin ecosystem creates lock-in',
        'Mobile apps drive daily usage',
      ],
      priorityScore: 92,
      recommendedForStudy: true,
      tags: ['ai', 'chatbot', 'llm', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'Cursor',
      slug: 'cursor',
      tagline: 'AI-first code editor',
      description:
        'VS Code fork with deep AI integration for code completion, chat, and intelligent editing.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.CodeAssistant,
      platforms: [Platform.Windows, Platform.macOS, Platform.Linux],
      targetAudiences: [TargetAudience.Developers],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 20,
      featureFlags: {
        hasAIGeneration: true,
        hasAIAssistant: true,
        hasCodeCompletion: true,
        hasChat: true,
        hasMultiFileEditing: true,
        hasFreeTier: true,
        hasSubscription: true,
      } as any,
      metrics: {
        totalUsers: 500000,
        monthlyActiveUsers: 200000,
        averageRating: 4.9,
        growthRateMonthly: 25,
      } as any,
      strengths: [
        'VS Code familiarity - zero learning curve',
        'Multi-file context awareness',
        'Composer for complex edits',
        'Tab-to-accept feels native',
        'Codebase understanding',
      ],
      weaknesses: [
        'Subscription cost for heavy use',
        'Dependent on external LLM providers',
        'Competition from GitHub Copilot',
      ],
      uniqueSellingPoints: [
        'Composer multi-file editing',
        'Codebase-aware suggestions',
        'VS Code extension compatibility',
        'Multiple model support',
      ],
      lessonsLearned: [
        'Developer tools can command premium',
        'Native IDE integration beats plugins',
        'Speed of iteration crucial',
      ],
      priorityScore: 88,
      recommendedForStudy: true,
      tags: ['ai', 'coding', 'ide', 'developer-tools', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'GitHub Copilot',
      slug: 'github-copilot',
      tagline: 'Your AI pair programmer',
      description:
        'AI coding assistant integrated into popular IDEs for code completion and suggestions.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.CodeAssistant,
      platforms: [Platform.CrossPlatform],
      targetAudiences: [TargetAudience.Developers, TargetAudience.Enterprise],
      relationship: ProductRelationship.Competitor,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.Subscription,
      hasFreeTier: false,
      freeTrialDays: 30,
      startingPrice: 10,
      featureFlags: {
        hasAIGeneration: true,
        hasCodeCompletion: true,
        hasChat: true,
        hasSubscription: true,
      } as any,
      metrics: {
        totalUsers: 1300000,
        averageRating: 4.7,
        enterpriseAdoption: 50000,
      } as any,
      strengths: [
        'GitHub integration and distribution',
        'Microsoft/OpenAI backing',
        'Enterprise trust and compliance',
        'IDE plugin approach',
        'Free for students/OSS',
      ],
      weaknesses: [
        'No free tier for professionals',
        'Context window limitations',
        'Plugin model less integrated than Cursor',
      ],
      uniqueSellingPoints: [
        'GitHub ecosystem integration',
        'Enterprise compliance features',
        'Works in any IDE',
      ],
      lessonsLearned: [
        'Distribution through existing tools key',
        'Enterprise sales is lucrative',
        'Plugin model enables reach but limits depth',
      ],
      priorityScore: 85,
      recommendedForStudy: true,
      tags: ['ai', 'coding', 'github', 'developer-tools', 'competitor'],
    },
    {
      id: uuidv4(),
      name: 'Perplexity AI',
      slug: 'perplexity-ai',
      tagline: 'Ask anything',
      description:
        'AI-powered answer engine combining LLMs with real-time web search for sourced answers.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.DataAnalysis,
      platforms: [Platform.Web, Platform.iOS, Platform.Android],
      targetAudiences: [TargetAudience.General, TargetAudience.Developers],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 20,
      featureFlags: {
        hasAIGeneration: true,
        hasWebSearch: true,
        hasCitations: true,
        hasUserAccounts: true,
        hasMobileApp: true,
        hasFreeTier: true,
      } as any,
      metrics: {
        totalUsers: 10000000,
        monthlyActiveUsers: 3000000,
        averageRating: 4.8,
        queriesPerMonth: 500000000,
      } as any,
      strengths: [
        'Citations build trust',
        'Real-time web access',
        'Clean, focused UI',
        'Multi-model options',
        'Good mobile experience',
      ],
      weaknesses: [
        'Less capable for creative tasks',
        'Search dependency',
        'Competition from Google/ChatGPT',
      ],
      uniqueSellingPoints: [
        'Every claim has source citations',
        'Real-time web search built-in',
        'Focus mode for domains',
        'Collections for research',
      ],
      lessonsLearned: [
        'Differentiate through sources/trust',
        'Focus on specific use case wins',
        'Search + AI is powerful combination',
      ],
      priorityScore: 82,
      recommendedForStudy: true,
      tags: ['ai', 'search', 'research', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'Midjourney',
      slug: 'midjourney',
      tagline: 'Imagine anything',
      description:
        'AI image generation through Discord with artistic and photorealistic capabilities.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.ImageGeneration,
      platforms: [Platform.Web],
      targetAudiences: [TargetAudience.Designers, TargetAudience.General],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.Subscription,
      hasFreeTier: false,
      startingPrice: 10,
      featureFlags: {
        hasAIGeneration: true,
        hasImageGeneration: true,
        hasSubscription: true,
        hasCommunity: true,
      } as any,
      metrics: {
        totalUsers: 16000000,
        monthlyActiveUsers: 5000000,
        revenueAnnual: 200000000,
        averageRating: 4.7,
      } as any,
      strengths: [
        'Best-in-class image quality',
        'Strong artistic style',
        'Active Discord community',
        'Continuous improvement',
        'Subscription-only = predictable revenue',
      ],
      weaknesses: [
        'Discord-only limits accessibility',
        'Learning curve for prompting',
        'No free tier',
        'Copyright concerns',
      ],
      uniqueSellingPoints: [
        'Industry-leading aesthetic quality',
        'Strong at artistic styles',
        'Vibrant community gallery',
        'v6 photorealism',
      ],
      lessonsLearned: [
        'Quality > accessibility initially',
        'Community creates stickiness',
        'Discord as platform worked',
        'Premium positioning viable',
      ],
      priorityScore: 80,
      recommendedForStudy: true,
      tags: ['ai', 'image-generation', 'creative', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'Replit Agent',
      slug: 'replit-agent',
      tagline: 'Build software with AI',
      description:
        'AI agent that can build entire applications from natural language descriptions.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.CodeAssistant,
      platforms: [Platform.Web],
      targetAudiences: [TargetAudience.Developers, TargetAudience.General],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 25,
      featureFlags: {
        hasAIGeneration: true,
        hasCodeExecution: true,
        hasDeployment: true,
        hasFreeTier: true,
        hasAgent: true,
      } as any,
      metrics: {
        totalUsers: 1000000,
        averageRating: 4.5,
      } as any,
      strengths: [
        'Full stack in browser',
        'Instant deployment',
        'No local setup needed',
        'Agentic code generation',
        'Good for learning',
      ],
      weaknesses: [
        'Performance limitations',
        'Complex apps challenging',
        'Subscription costs add up',
      ],
      uniqueSellingPoints: [
        'Natural language to deployed app',
        'Zero setup required',
        'Integrated hosting',
        'Collaborative coding',
      ],
      lessonsLearned: [
        'Agentic coding is the next frontier',
        'End-to-end experience matters',
        'Non-developers as new market',
      ],
      priorityScore: 78,
      recommendedForStudy: true,
      tags: ['ai', 'coding', 'agent', 'development', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'v0 by Vercel',
      slug: 'v0-vercel',
      tagline: 'Generate UI with AI',
      description:
        'AI-powered UI generation tool that creates React components from natural language.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.CodeAssistant,
      platforms: [Platform.Web],
      targetAudiences: [TargetAudience.Developers],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 20,
      featureFlags: {
        hasAIGeneration: true,
        hasCodeGeneration: true,
        hasUIGeneration: true,
        hasFreeTier: true,
      } as any,
      metrics: {
        totalUsers: 500000,
        averageRating: 4.6,
      } as any,
      strengths: [
        'Shadcn/UI integration',
        'Vercel ecosystem',
        'High quality output',
        'Easy iteration',
      ],
      weaknesses: [
        'React/Next.js only',
        'Limited customization',
        'Credit system frustrating',
      ],
      uniqueSellingPoints: [
        'Production-ready React code',
        'Shadcn/UI components',
        'Visual iteration',
        'Direct Vercel deploy',
      ],
      lessonsLearned: [
        'Vertical specialization wins',
        'Quality beats generalization',
        'Developer experience matters',
      ],
      priorityScore: 75,
      recommendedForStudy: true,
      tags: ['ai', 'ui', 'react', 'developer-tools', 'reference'],
    },
    {
      id: uuidv4(),
      name: 'Devin',
      slug: 'devin',
      tagline: 'The first AI software engineer',
      description:
        'Autonomous AI software engineer that can plan, code, debug, and deploy software.',
      category: ProductCategory.AIAssistant,
      subcategory: ProductSubcategory.CodeAssistant,
      platforms: [Platform.Web],
      targetAudiences: [TargetAudience.Enterprise, TargetAudience.Developers],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Beta,
      monetizationModel: MonetizationModel.Subscription,
      hasFreeTier: false,
      startingPrice: 500,
      featureFlags: {
        hasAIGeneration: true,
        hasAgent: true,
        hasAutonomous: true,
        hasPlanning: true,
        hasDebugging: true,
      } as any,
      metrics: {
        totalUsers: 10000,
        averageRating: 4.3,
        tasksCompleted: 50000,
      } as any,
      strengths: [
        'Truly autonomous operation',
        'End-to-end task completion',
        'Learning from feedback',
        'First mover in autonomous coding',
      ],
      weaknesses: [
        'Expensive ($500/mo)',
        'Limited access',
        'Complex tasks still challenging',
        'Trust/verification needs',
      ],
      uniqueSellingPoints: [
        'First truly autonomous AI engineer',
        'Plans and executes independently',
        'Uses tools like a human would',
        'Continuous improvement',
      ],
      lessonsLearned: [
        'Autonomous agents are next evolution',
        'Enterprise willing to pay premium',
        'Trust building is critical',
      ],
      priorityScore: 70,
      recommendedForStudy: true,
      tags: ['ai', 'agent', 'autonomous', 'coding', 'reference'],
    },

    // ==========================================
    // ONLINE COURSES
    // ==========================================
    {
      id: uuidv4(),
      name: 'Google Data Analytics Certificate',
      slug: 'google-data-analytics',
      tagline: 'Launch your career in data analytics',
      description:
        'Professional certificate program by Google covering data analysis, visualization, and SQL.',
      category: ProductCategory.Certification,
      subcategory: ProductSubcategory.DataScience,
      platforms: [Platform.Web],
      targetAudiences: [TargetAudience.Adults, TargetAudience.Students],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.Subscription,
      hasFreeTier: false,
      freeTrialDays: 7,
      startingPrice: 39,
      featureFlags: {
        hasUserAccounts: true,
        hasProgress: true,
        hasAchievements: true,
        hasContentCreation: false,
      } as any,
      metrics: {
        totalUsers: 2000000,
        averageRating: 4.8,
        reviewCount: 150000,
      } as any,
      strengths: ['Google brand', 'Job-ready skills', 'Capstone project'],
      priorityScore: 85,
      recommendedForStudy: true,
      tags: ['course', 'data-analytics', 'google', 'certificate'],
    },

    // ==========================================
    // PRODUCTIVITY / SAAS
    // ==========================================
    {
      id: uuidv4(),
      name: 'Notion',
      slug: 'notion-app',
      tagline: 'Your connected workspace',
      description:
        'All-in-one workspace combining notes, docs, wikis, and databases.',
      category: ProductCategory.SaaSApp,
      subcategory: ProductSubcategory.NotesTaking,
      platforms: [
        Platform.Web,
        Platform.iOS,
        Platform.Android,
        Platform.Windows,
        Platform.macOS,
      ],
      targetAudiences: [
        TargetAudience.Adults,
        TargetAudience.Startups,
        TargetAudience.Enterprise,
      ],
      relationship: ProductRelationship.Competitor,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 10,
      featureFlags: {
        hasUserAccounts: true,
        hasTeams: true,
        hasRealTimeCollab: true,
        hasTemplates: true,
        hasAPI: true,
        hasAIGeneration: true,
        hasMobileApp: true,
        hasFreeTier: true,
        hasSubscription: true,
      } as any,
      metrics: {
        totalUsers: 30000000,
        monthlyActiveUsers: 10000000,
        averageRating: 4.7,
      } as any,
      strengths: ['Flexibility', 'Database blocks', 'Template gallery'],
      weaknesses: ['Learning curve', 'Offline support'],
      priorityScore: 88,
      recommendedForStudy: true,
      tags: ['productivity', 'notes', 'database', 'wiki'],
    },

    // ==========================================
    // FAMILY APPS
    // ==========================================
    {
      id: uuidv4(),
      name: 'Life360',
      slug: 'life360-app',
      tagline: 'Keep your family safe',
      description:
        'Family locator and safety app with location sharing, crash detection, and driving insights.',
      category: ProductCategory.FamilyApp,
      subcategory: ProductSubcategory.LocationSharing,
      platforms: [Platform.iOS, Platform.Android],
      targetAudiences: [TargetAudience.Parents, TargetAudience.Families],
      relationship: ProductRelationship.Competitor,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 8,
      featureFlags: {
        hasUserAccounts: true,
        hasMobileApp: true,
        hasPushNotifications: true,
        hasFreeTier: true,
        hasSubscription: true,
      } as any,
      metrics: {
        totalUsers: 50000000,
        monthlyActiveUsers: 35000000,
        averageRating: 4.5,
      } as any,
      strengths: ['Real-time location', 'Crash detection', 'Place alerts'],
      weaknesses: ['Battery usage', 'Privacy concerns'],
      priorityScore: 82,
      recommendedForStudy: true,
      tags: ['family', 'location', 'safety', 'parenting'],
    },
    {
      id: uuidv4(),
      name: 'OurHome',
      slug: 'ourhome',
      tagline: 'Family chores made easy',
      description:
        'Chore and reward system for families with task assignments and point tracking.',
      category: ProductCategory.FamilyApp,
      subcategory: ProductSubcategory.TaskManagement,
      platforms: [Platform.iOS, Platform.Android, Platform.Web],
      targetAudiences: [
        TargetAudience.Parents,
        TargetAudience.Families,
        TargetAudience.Children,
      ],
      relationship: ProductRelationship.Reference,
      status: ProductStatus.Growing,
      monetizationModel: MonetizationModel.Freemium,
      hasFreeTier: true,
      startingPrice: 5,
      featureFlags: {
        hasUserAccounts: true,
        hasMobileApp: true,
        hasRewards: true,
        hasProgress: true,
        hasPushNotifications: true,
        hasFreeTier: true,
      } as any,
      metrics: {
        totalUsers: 2000000,
        averageRating: 4.6,
      } as any,
      strengths: ['Gamification', 'Kid-friendly', 'Reward system'],
      uniqueSellingPoints: ['Point-based rewards', 'Family banking'],
      priorityScore: 75,
      recommendedForStudy: true,
      tags: ['family', 'chores', 'kids', 'rewards', 'gamification'],
    },

    // ==========================================
    // REFERENCE GAMES (Top Roblox)
    // ==========================================
    {
      id: uuidv4(),
      name: 'Pet Simulator X',
      slug: 'pet-simulator-x',
      tagline: 'Collect and hatch epic pets!',
      description:
        'Roblox game where players collect coins, hatch eggs, and collect pets with trading.',
      category: ProductCategory.Game,
      subcategory: ProductSubcategory.Simulation,
      platforms: [Platform.Roblox],
      targetAudiences: [TargetAudience.Children, TargetAudience.Teens],
      relationship: ProductRelationship.Inspiration,
      status: ProductStatus.Mature,
      monetizationModel: MonetizationModel.InAppPurchases,
      hasFreeTier: true,
      launchDate: new Date('2021-04-14'),
      featureFlags: {
        hasMultiplayer: true,
        hasLeaderboards: true,
        hasAchievements: true,
        hasRewards: true,
        hasProgress: true,
        hasMicroTransactions: true,
        hasTrading: true,
        hasCollection: true,
        hasEvents: true,
      } as any,
      metrics: {
        totalUsers: 100000000,
        monthlyActiveUsers: 20000000,
        dailyActiveUsers: 5000000,
        concurrentPlayers: 150000,
        revenueMonthly: 3000000,
        revenueAnnual: 36000000,
        averageRating: 4.8,
        reviewCount: 800000,
        retentionDay1: 58,
        retentionDay7: 35,
        retentionDay30: 16,
      } as any,
      strengths: [
        'Deeply satisfying collection loop',
        'Massive variety of pets with clear rarity tiers',
        'Regular weekly updates keep content fresh',
        'Strong social features - trading creates economy',
        'YouTuber partnerships drive awareness',
        'Events create urgency and FOMO',
      ],
      uniqueSellingPoints: [
        'Huge variety of pets',
        'Regular updates',
        'Events system',
        'Trading economy',
        'Egg hatching anticipation',
      ],
      lessonsLearned: [
        'Update frequency matters more than update size',
        'YouTuber codes drive massive traffic spikes',
        'Trading adds 10x retention vs collect-only games',
        'Rarity tiers should be visually distinct',
      ],
      priorityScore: 98,
      recommendedForStudy: true,
      tags: ['roblox', 'game', 'pets', 'simulator', 'collection', 'reference'],
    },
  ];

  // Save to database
  for (const company of companies) {
    const fullCompany: CompanyDto = {
      id: company.id!,
      creationTime: now,
      lastModificationTime: now,
      creatorId: 'seed',
      lastModifierId: 'seed',
      name: company.name!,
      slug: company.slug!,
      description: company.description!,
      tagline: company.tagline,
      logoUrl: company.logoUrl,
      companyType: company.companyType!,
      relationship: company.relationship!,
      size: company.size!,
      stage: company.stage!,
      foundedYear: company.foundedYear,
      contact: company.contact || { website: '' },
      funding: company.funding || { totalFunding: 0, isPublic: false },
      metrics: company.metrics || {},
      productIds: [],
      strengths: company.strengths || [],
      weaknesses: company.weaknesses || [],
      opportunities: [],
      threats: [],
      targetMarkets: company.targetMarkets || [],
      primaryAudience: '',
      competitorIds: [],
      strategicNotes: '',
      threatLevel: company.threatLevel || 'Low',
      partnershipPotential: 5,
      acquisitionTarget: false,
      tags: company.tags || [],
    };
    storage.create('companies', fullCompany);
  }

  for (const product of products) {
    const fullProduct: ProductDto = {
      id: product.id!,
      creationTime: now,
      lastModificationTime: now,
      creatorId: 'seed',
      lastModifierId: 'seed',
      name: product.name!,
      slug: product.slug!,
      tagline: product.tagline || '',
      description: product.description!,
      screenshotUrls: [],
      category: product.category!,
      subcategory: product.subcategory || ProductSubcategory.Other,
      platforms: product.platforms || [],
      targetAudiences: product.targetAudiences || [],
      relationship: product.relationship!,
      status: product.status || ProductStatus.Launched,
      featureFlags: (product.featureFlags as any) || {},
      features: [],
      monetizationModel: product.monetizationModel || MonetizationModel.Free,
      pricingTiers: [],
      hasFreeTier: product.hasFreeTier ?? true,
      freeTrialDays: product.freeTrialDays,
      startingPrice: product.startingPrice,
      metrics: (product.metrics as any) || {},
      strengths: product.strengths || [],
      weaknesses: product.weaknesses || [],
      uniqueSellingPoints: product.uniqueSellingPoints || [],
      lessonsLearned: [],
      competitorIds: [],
      marketPosition: 'Niche',
      differentiators: [],
      threatLevel: 'Low',
      priorityScore: product.priorityScore || 50,
      recommendedForStudy: product.recommendedForStudy ?? false,
      replicationDifficulty: 'Medium',
      strategicNotes: '',
      technicalNotes: '',
      tags: product.tags || [],
    };
    storage.create('products', fullProduct);
  }

  console.log(
    `✅ Seeded ${companies.length} companies and ${products.length} products`,
  );
}

// Run if called directly
if (require.main === module) {
  const storage = new JsonStorageService();
  seedProductDatabase(storage);
}
