import { JsonStorageService } from './json-storage.service';
import {
  FeatureDto,
  ProductFeatureDto,
  FeatureCategory,
  FeatureImportance,
  FeaturePriority,
  FeatureStatus,
  ComplexityLevel,
  ImpactLevel,
  QualityLevel,
} from '../shared/dtos/feature.dto';

/**
 * Seed comprehensive feature data for competitive analysis matrix
 */
export function seedFeatures(storage: JsonStorageService): void {
  console.log('🎮 Seeding Feature Intelligence data...');

  // ==========================================
  // FEATURES - Comprehensive game feature set
  // ==========================================
  const features: FeatureDto[] = [
    // CORE GAMEPLAY
    {
      id: 'feat-collection',
      name: 'Collection System',
      slug: 'collection-system',
      description:
        'Players collect items, pets, fish, dragons, etc. Core loop for most simulators.',
      category: FeatureCategory.Core,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes:
        'Every successful simulator has collection at its core. Key differentiator is WHAT you collect.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 5,
      retentionImpact: ImpactLevel.Critical,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Pet Simulator X has masterful egg mechanics',
      tags: ['core', 'loop', 'essential'],
    },
    {
      id: 'feat-trading',
      name: 'Player Trading',
      slug: 'player-trading',
      description:
        'Peer-to-peer item/pet trading system. Creates player economy and social bonds.',
      category: FeatureCategory.Social,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Trading creates emergent economy. Need scam protection. Consider trade history.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 10,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Adopt Me trading with confirmation screens',
      tags: ['social', 'economy', 'multiplayer'],
    },
    {
      id: 'feat-breeding',
      name: 'Breeding/Fusion System',
      slug: 'breeding-fusion',
      description:
        'Combine two items to create new variants. Adds depth and rarity creation.',
      category: FeatureCategory.Core,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'Breeding adds genetic interest. Fusion simpler to implement. Both create item sinks.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Dragon breeding in Dragon Adventures',
      tags: ['depth', 'genetics', 'crafting'],
    },
    {
      id: 'feat-evolution',
      name: 'Evolution/Leveling',
      slug: 'evolution-leveling',
      description:
        'Items/pets grow stronger over time or through actions. Progression hook.',
      category: FeatureCategory.Progression,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Evolution creates attachment. Visible transformations are highly satisfying.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 7,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Pet aging in Adopt Me',
      tags: ['progression', 'growth', 'attachment'],
    },

    // RETENTION & ENGAGEMENT
    {
      id: 'feat-daily-rewards',
      name: 'Daily Rewards',
      slug: 'daily-rewards',
      description:
        'Login rewards that escalate over consecutive days. Core retention mechanic.',
      category: FeatureCategory.Retention,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes:
        'Standard feature. 7-day cycles work well. Big reward on day 7/30. Reset on miss is controversial.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 2,
      retentionImpact: ImpactLevel.Critical,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Most games have this',
      tags: ['retention', 'login', 'essential'],
    },
    {
      id: 'feat-events',
      name: 'Limited-Time Events',
      slug: 'limited-events',
      description:
        'Seasonal/holiday events with exclusive rewards. FOMO driver.',
      category: FeatureCategory.Content,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Plan event calendar 6 months ahead. Holiday events are expected. Exclusive items drive urgency.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Adopt Me holiday events are legendary',
      tags: ['content', 'fomo', 'seasonal'],
    },
    {
      id: 'feat-quests',
      name: 'Quest/Mission System',
      slug: 'quests-missions',
      description:
        'Objectives to complete for rewards. Provides direction and goals.',
      category: FeatureCategory.Progression,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Daily + Weekly + Seasonal quests. Tiered difficulty. Clear rewards displayed upfront.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 7,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Blox Fruits quest chains',
      tags: ['progression', 'goals', 'engagement'],
    },
    {
      id: 'feat-achievements',
      name: 'Achievement System',
      slug: 'achievements',
      description: 'Long-term goals with badges/titles. Completionist appeal.',
      category: FeatureCategory.Progression,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'Categories: Collection, Progression, Social, Special. Visible badges in profile.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 5,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Badge systems common across platform',
      tags: ['progression', 'completionist', 'flex'],
    },
    {
      id: 'feat-leaderboards',
      name: 'Leaderboards',
      slug: 'leaderboards',
      description:
        'Competitive rankings for various metrics. Social comparison driver.',
      category: FeatureCategory.Social,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Global, friends, weekly, all-time. Multiple categories. Visible rewards for top spots.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 5,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Fish It! real-time leaderboards',
      tags: ['social', 'competition', 'flex'],
    },

    // MONETIZATION
    {
      id: 'feat-premium-currency',
      name: 'Premium Currency',
      slug: 'premium-currency',
      description:
        'Robux-purchasable currency for in-game purchases. Primary revenue stream.',
      category: FeatureCategory.Monetization,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes:
        'Standard on Roblox. Consider dual currency (soft + hard). Bundles with bonuses.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 3,
      retentionImpact: ImpactLevel.Low,
      monetizationImpact: ImpactLevel.Critical,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Every top game',
      tags: ['monetization', 'robux', 'essential'],
    },
    {
      id: 'feat-gacha',
      name: 'Gacha/Egg System',
      slug: 'gacha-eggs',
      description:
        'Random reward boxes with varying rarities. High-margin monetization.',
      category: FeatureCategory.Monetization,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Show odds (Roblox requires). Tiered eggs. Pity system optional. Visible rolling animation.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 7,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Critical,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Pet Simulator X egg hatching',
      tags: ['monetization', 'luck', 'gambling'],
    },
    {
      id: 'feat-battle-pass',
      name: 'Battle/Season Pass',
      slug: 'battle-pass',
      description:
        'Seasonal progression with free and premium tracks. Recurring revenue.',
      category: FeatureCategory.Monetization,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'Free track must be compelling. Premium track = exclusive items. XP from gameplay.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Fortnite pioneered, now everywhere',
      tags: ['monetization', 'season', 'progression'],
    },
    {
      id: 'feat-vip-gamepass',
      name: 'VIP/Gamepass',
      slug: 'vip-gamepass',
      description:
        'One-time purchase for permanent perks. Lower commitment than subscriptions.',
      category: FeatureCategory.Monetization,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Multiple tiers possible. Clear value proposition. Visible VIP badge.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 2,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Standard Roblox pattern',
      tags: ['monetization', 'gamepass', 'perks'],
    },

    // SOCIAL & MULTIPLAYER
    {
      id: 'feat-multiplayer',
      name: 'Multiplayer/Co-op',
      slug: 'multiplayer-coop',
      description:
        'Play with other players in shared world. Core Roblox expectation.',
      category: FeatureCategory.Social,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes:
        'Roblox is inherently multiplayer. Even single-player games benefit from presence.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 0,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.Critical,
      bestPracticeExample: 'Built into platform',
      tags: ['social', 'multiplayer', 'essential'],
    },
    {
      id: 'feat-guilds',
      name: 'Guilds/Clans',
      slug: 'guilds-clans',
      description:
        'Player groups with shared goals and perks. Social retention driver.',
      category: FeatureCategory.Social,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'Guild wars, shared goals, chat, ranks. Creates social obligation to return.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Clan systems in competitive games',
      tags: ['social', 'groups', 'retention'],
    },
    {
      id: 'feat-friends',
      name: 'Friend Features',
      slug: 'friend-features',
      description:
        'Friend-specific bonuses, invites, and features. Organic growth driver.',
      category: FeatureCategory.Social,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'Friend referral bonuses. Friend leaderboards. Play together bonuses.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 3,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Critical,
      bestPracticeExample: 'Roblox friend system integration',
      tags: ['social', 'friends', 'viral'],
    },
    {
      id: 'feat-chat',
      name: 'Chat System',
      slug: 'chat-system',
      description:
        'In-game text communication. Roblox provides base, but can enhance.',
      category: FeatureCategory.Social,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes: 'Roblox chat is default. Consider quick chat, emotes, stickers.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 2,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Roblox default + custom emotes',
      tags: ['social', 'communication', 'moderation'],
    },

    // CONTENT & VARIETY
    {
      id: 'feat-customization',
      name: 'Customization/Cosmetics',
      slug: 'customization',
      description:
        'Player/pet appearance customization. Self-expression driver.',
      category: FeatureCategory.Content,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'High monetization potential. Regular new items. Seasonal exclusives.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 7,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Dress To Impress cosmetic depth',
      tags: ['content', 'cosmetics', 'expression'],
    },
    {
      id: 'feat-housing',
      name: 'Housing/Decorating',
      slug: 'housing-decorating',
      description:
        'Player-owned spaces they can customize. Deep engagement feature.',
      category: FeatureCategory.Content,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'High dev cost but high engagement. Furniture = monetization. Tours create social.',
      implementationComplexity: ComplexityLevel.VeryComplex,
      estimatedDevDays: 21,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Adopt Me house customization',
      tags: ['content', 'housing', 'building'],
    },
    {
      id: 'feat-worlds',
      name: 'Multiple Worlds/Areas',
      slug: 'multiple-worlds',
      description: 'Different themed areas to explore. Content expansion path.',
      category: FeatureCategory.Content,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes:
        'New worlds for updates. Each world = new items. Progression gating.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Blox Fruits sea expansions',
      tags: ['content', 'expansion', 'exploration'],
    },

    // COMBAT & COMPETITION
    {
      id: 'feat-pvp',
      name: 'PvP Combat',
      slug: 'pvp-combat',
      description:
        'Player versus player battles. Competitive engagement driver.',
      category: FeatureCategory.Core,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'Not for all games. Requires careful balance. Arenas separate from main game.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Blox Fruits combat system',
      tags: ['combat', 'pvp', 'competitive'],
    },
    {
      id: 'feat-pve',
      name: 'PvE/Boss Battles',
      slug: 'pve-bosses',
      description:
        'Cooperative battles against AI enemies. Social bonding through challenge.',
      category: FeatureCategory.Core,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes: 'Raid bosses create events. Scaling difficulty. Loot tables.',
      implementationComplexity: ComplexityLevel.Complex,
      estimatedDevDays: 14,
      retentionImpact: ImpactLevel.High,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Blox Fruits raid dungeons',
      tags: ['combat', 'pve', 'bosses'],
    },
    {
      id: 'feat-minigames',
      name: 'Minigames',
      slug: 'minigames',
      description: 'Short competitive games within main game. Session variety.',
      category: FeatureCategory.Content,
      importance: FeatureImportance.Low,
      priority: FeaturePriority.P3,
      notes: 'Racing, fishing tournaments, etc. Break up main loop.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 7,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Medium,
      bestPracticeExample: 'Various game minigame events',
      tags: ['content', 'casual', 'variety'],
    },

    // SAFETY & MODERATION
    {
      id: 'feat-parental-controls',
      name: 'Parental Controls',
      slug: 'parental-controls',
      description: 'Features for parent oversight and child safety.',
      category: FeatureCategory.Safety,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes:
        'Roblox provides base. Consider spending limits, play time, chat restrictions.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 5,
      retentionImpact: ImpactLevel.Low,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Roblox parental dashboard',
      tags: ['safety', 'family', 'trust'],
    },
    {
      id: 'feat-moderation',
      name: 'Content Moderation',
      slug: 'content-moderation',
      description:
        'Systems to prevent abuse, scams, and inappropriate content.',
      category: FeatureCategory.Safety,
      importance: FeatureImportance.High,
      priority: FeaturePriority.P1,
      notes: 'Report systems. Trade confirmations. Chat filtering. Age gates.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 5,
      retentionImpact: ImpactLevel.Medium,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Roblox moderation + game-specific',
      tags: ['safety', 'moderation', 'trust'],
    },

    // UX & QUALITY OF LIFE
    {
      id: 'feat-tutorial',
      name: 'Tutorial/Onboarding',
      slug: 'tutorial-onboarding',
      description: 'First-time user experience guiding new players.',
      category: FeatureCategory.UX,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes:
        'Critical for retention. Show value in 30 seconds. Skip option for returning.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 5,
      retentionImpact: ImpactLevel.Critical,
      monetizationImpact: ImpactLevel.Medium,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Simple games often skip entirely',
      tags: ['ux', 'onboarding', 'retention'],
    },
    {
      id: 'feat-mobile',
      name: 'Mobile Optimization',
      slug: 'mobile-optimization',
      description: 'Touch controls and UI optimized for mobile play.',
      category: FeatureCategory.Technical,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes: '60%+ of Roblox is mobile. Touch-first design. Simple UI.',
      implementationComplexity: ComplexityLevel.Medium,
      estimatedDevDays: 7,
      retentionImpact: ImpactLevel.Critical,
      monetizationImpact: ImpactLevel.High,
      viralityImpact: ImpactLevel.High,
      bestPracticeExample: 'Fish It! one-tap mobile design',
      tags: ['technical', 'mobile', 'essential'],
    },
    {
      id: 'feat-autosave',
      name: 'Auto-Save/Cloud Save',
      slug: 'autosave-cloud',
      description: 'Automatic progress saving. Expected standard.',
      category: FeatureCategory.Technical,
      importance: FeatureImportance.Critical,
      priority: FeaturePriority.P0,
      notes:
        'Roblox DataStore handles this. Implement properly. Backup systems.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 2,
      retentionImpact: ImpactLevel.Critical,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Standard implementation',
      tags: ['technical', 'data', 'essential'],
    },
    {
      id: 'feat-settings',
      name: 'Settings/Options',
      slug: 'settings-options',
      description: 'Player-configurable game settings.',
      category: FeatureCategory.UX,
      importance: FeatureImportance.Medium,
      priority: FeaturePriority.P2,
      notes: 'Graphics, sound, controls, notifications. Accessibility options.',
      implementationComplexity: ComplexityLevel.Simple,
      estimatedDevDays: 2,
      retentionImpact: ImpactLevel.Low,
      monetizationImpact: ImpactLevel.Low,
      viralityImpact: ImpactLevel.Low,
      bestPracticeExample: 'Standard settings menu',
      tags: ['ux', 'settings', 'accessibility'],
    },
  ];

  // ==========================================
  // PRODUCT-FEATURE MATRIX
  // ==========================================
  // Map features to specific products

  // Get product IDs (we'll use slugs to reference)
  const productFeatures: ProductFeatureDto[] = [
    // Dragon Legends
    {
      productId: 'dragon-legends',
      featureId: 'feat-collection',
      status: FeatureStatus.InProgress,
      implementationQuality: QualityLevel.Good,
      whyHave: 'Core loop - collecting dragons is the game',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-trading',
      status: FeatureStatus.Planned,
      whyHave: 'Dragon trading creates economy and social',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-breeding',
      status: FeatureStatus.InProgress,
      implementationQuality: QualityLevel.Good,
      whyHave: 'Unique differentiator - dragon genetics',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-evolution',
      status: FeatureStatus.Planned,
      whyHave: 'Dragon growth adds attachment',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-daily-rewards',
      status: FeatureStatus.Planned,
      whyHave: 'Standard retention feature',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-events',
      status: FeatureStatus.Planned,
      whyHave: 'Content pipeline for updates',
      shouldHave: true,
      priority: FeaturePriority.P2,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-gacha',
      status: FeatureStatus.InProgress,
      implementationQuality: QualityLevel.Adequate,
      whyHave: 'Dragon eggs = gacha mechanic',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-pvp',
      status: FeatureStatus.Planned,
      whyHave: 'Dragon battles for competitive play',
      shouldHave: true,
      priority: FeaturePriority.P2,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-guilds',
      status: FeatureStatus.Planned,
      whyHave: 'Dragon guilds for group content',
      shouldHave: true,
      priority: FeaturePriority.P2,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-multiplayer',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
      whyHave: 'Roblox standard',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-leaderboards',
      status: FeatureStatus.Planned,
      whyHave: 'Competition and flex',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-mobile',
      status: FeatureStatus.InProgress,
      implementationQuality: QualityLevel.Adequate,
      whyHave: 'Majority of players are mobile',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-tutorial',
      status: FeatureStatus.Planned,
      whyHave: 'First impression matters',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'dragon-legends',
      featureId: 'feat-housing',
      status: FeatureStatus.NotPlanned,
      whyNotHave: 'Not core to dragon game, maybe dragon lair later',
      shouldHave: false,
      priority: FeaturePriority.P4,
    },

    // Lucky Fish Legends
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-collection',
      status: FeatureStatus.InProgress,
      implementationQuality: QualityLevel.Good,
      whyHave: 'Core loop - fish collection',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-trading',
      status: FeatureStatus.Planned,
      whyHave: 'Fish trading for rare catches',
      shouldHave: true,
      priority: FeaturePriority.P2,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-breeding',
      status: FeatureStatus.NotPlanned,
      whyNotHave: 'Fish fusion instead of breeding',
      shouldHave: false,
      priority: FeaturePriority.P3,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-daily-rewards',
      status: FeatureStatus.Planned,
      whyHave: 'Standard feature',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-events',
      status: FeatureStatus.Planned,
      whyHave: 'Seasonal fish species',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-housing',
      status: FeatureStatus.InProgress,
      implementationQuality: QualityLevel.Good,
      whyHave: 'Aquarium building is core feature',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-leaderboards',
      status: FeatureStatus.Planned,
      whyHave: 'Fishing competitions',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-minigames',
      status: FeatureStatus.Planned,
      whyHave: 'Fishing tournaments',
      shouldHave: true,
      priority: FeaturePriority.P2,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-worlds',
      status: FeatureStatus.Planned,
      whyHave: 'Different fishing biomes',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-pvp',
      status: FeatureStatus.NotPlanned,
      whyNotHave: 'Relaxing game, no combat',
      shouldHave: false,
      priority: FeaturePriority.P4,
    },
    {
      productId: 'lucky-fish-legends',
      featureId: 'feat-mobile',
      status: FeatureStatus.Planned,
      whyHave: 'Core platform',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },

    // Family Quest
    {
      productId: 'family-quest',
      featureId: 'feat-quests',
      status: FeatureStatus.Planned,
      whyHave: 'Core gameplay - family quests',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'family-quest',
      featureId: 'feat-multiplayer',
      status: FeatureStatus.Planned,
      whyHave: 'Parent-child co-op is core',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'family-quest',
      featureId: 'feat-achievements',
      status: FeatureStatus.Planned,
      whyHave: 'Family achievements together',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'family-quest',
      featureId: 'feat-parental-controls',
      status: FeatureStatus.Planned,
      whyHave: 'Core for family game',
      shouldHave: true,
      priority: FeaturePriority.P0,
    },
    {
      productId: 'family-quest',
      featureId: 'feat-chat',
      status: FeatureStatus.Planned,
      whyHave: 'Safe family chat',
      shouldHave: true,
      priority: FeaturePriority.P1,
    },
    {
      productId: 'family-quest',
      featureId: 'feat-pvp',
      status: FeatureStatus.NotPlanned,
      whyNotHave: 'Cooperative not competitive',
      shouldHave: false,
      priority: FeaturePriority.P4,
    },
    {
      productId: 'family-quest',
      featureId: 'feat-gacha',
      status: FeatureStatus.NotPlanned,
      whyNotHave: 'Family-friendly, no gambling mechanics',
      shouldHave: false,
      priority: FeaturePriority.P4,
    },

    // Fish It! (Competitor)
    {
      productId: 'fish-it',
      featureId: 'feat-collection',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Simple but effective fish collection',
    },
    {
      productId: 'fish-it',
      featureId: 'feat-leaderboards',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Real-time leaderboards drive competition',
    },
    {
      productId: 'fish-it',
      featureId: 'feat-gacha',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
      implementationNotes: 'Rare fish RNG mechanics',
    },
    {
      productId: 'fish-it',
      featureId: 'feat-mobile',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'One-tap design perfect for mobile',
    },
    {
      productId: 'fish-it',
      featureId: 'feat-multiplayer',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
    },
    {
      productId: 'fish-it',
      featureId: 'feat-trading',
      status: FeatureStatus.NotApplicable,
    },
    {
      productId: 'fish-it',
      featureId: 'feat-housing',
      status: FeatureStatus.NotApplicable,
    },
    {
      productId: 'fish-it',
      featureId: 'feat-pvp',
      status: FeatureStatus.NotApplicable,
    },

    // Adopt Me! (Competitor)
    {
      productId: 'adopt-me',
      featureId: 'feat-collection',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Pet collection mastered',
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-trading',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Gold standard for trading UX',
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-evolution',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Pet aging/neon system is iconic',
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-housing',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Deep house customization',
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-events',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Event calendar is industry leading',
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-daily-rewards',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-gacha',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
      implementationNotes: 'Egg hatching with visible odds',
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-mobile',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-multiplayer',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-pvp',
      status: FeatureStatus.NotApplicable,
    },
    {
      productId: 'adopt-me',
      featureId: 'feat-leaderboards',
      status: FeatureStatus.NotApplicable,
    },

    // Blox Fruits (Competitor)
    {
      productId: 'blox-fruits',
      featureId: 'feat-pvp',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Deep combat system',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-pve',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Raid dungeons and bosses',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-quests',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Quest chains with story',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-evolution',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
      implementationNotes: 'Leveling and abilities',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-worlds',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Three seas with unique content',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-trading',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
      implementationNotes: 'Fruit trading',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-guilds',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-leaderboards',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-gacha',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
      implementationNotes: 'Fruit spinning mechanic',
    },
    {
      productId: 'blox-fruits',
      featureId: 'feat-mobile',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Adequate,
      implementationNotes: 'Combat harder on mobile',
    },

    // Pet Simulator X (Reference)
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-collection',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Pet collection perfected',
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-gacha',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Egg mechanics are S-tier',
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-trading',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-evolution',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Golden/Rainbow evolution',
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-worlds',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
      implementationNotes: 'Regular new world releases',
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-events',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Excellent,
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-leaderboards',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
    },
    {
      productId: 'pet-simulator-x',
      featureId: 'feat-guilds',
      status: FeatureStatus.Implemented,
      implementationQuality: QualityLevel.Good,
    },
  ];

  // Save to storage
  storage.setCollection('features', features);
  storage.setCollection('product-features', productFeatures);

  console.log(`  ✅ Seeded ${features.length} features`);
  console.log(`  ✅ Seeded ${productFeatures.length} product-feature mappings`);
}
