// Country flags data with difficulty ratings
// Difficulty: 1 = Easy (well-known), 2 = Medium, 3 = Hard

export interface Country {
  code: string;
  name: string;
  flag: string; // emoji flag
  continent: string;
  difficulty: 1 | 2 | 3;
}

export const COUNTRIES: Country[] = [
  // Easy flags (difficulty 1) - Well-known countries
  { code: 'US', name: 'United States', flag: '🇺🇸', continent: 'North America', difficulty: 1 },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', continent: 'Europe', difficulty: 1 },
  { code: 'FR', name: 'France', flag: '🇫🇷', continent: 'Europe', difficulty: 1 },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', continent: 'Europe', difficulty: 1 },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', continent: 'Asia', difficulty: 1 },
  { code: 'CN', name: 'China', flag: '🇨🇳', continent: 'Asia', difficulty: 1 },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', continent: 'South America', difficulty: 1 },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', continent: 'North America', difficulty: 1 },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', continent: 'Oceania', difficulty: 1 },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', continent: 'Europe', difficulty: 1 },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', continent: 'Europe', difficulty: 1 },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', continent: 'North America', difficulty: 1 },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', continent: 'Europe', difficulty: 1 },
  { code: 'IN', name: 'India', flag: '🇮🇳', continent: 'Asia', difficulty: 1 },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', continent: 'Asia', difficulty: 1 },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', continent: 'South America', difficulty: 1 },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', continent: 'Africa', difficulty: 1 },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', continent: 'Europe', difficulty: 1 },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', continent: 'Europe', difficulty: 1 },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', continent: 'Europe', difficulty: 1 },
  
  // Medium flags (difficulty 2)
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', continent: 'Europe', difficulty: 2 },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', continent: 'Europe', difficulty: 2 },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', continent: 'Europe', difficulty: 2 },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', continent: 'Europe', difficulty: 2 },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', continent: 'Europe', difficulty: 2 },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', continent: 'Europe', difficulty: 2 },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', continent: 'Europe', difficulty: 2 },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', continent: 'Europe', difficulty: 2 },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', continent: 'Europe', difficulty: 2 },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', continent: 'Asia', difficulty: 2 },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', continent: 'Africa', difficulty: 2 },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', continent: 'Asia', difficulty: 2 },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', continent: 'Asia', difficulty: 2 },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', continent: 'Asia', difficulty: 2 },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', continent: 'Asia', difficulty: 2 },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', continent: 'Asia', difficulty: 2 },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', continent: 'Asia', difficulty: 2 },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', continent: 'Oceania', difficulty: 2 },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', continent: 'South America', difficulty: 2 },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', continent: 'South America', difficulty: 2 },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', continent: 'South America', difficulty: 2 },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', continent: 'South America', difficulty: 2 },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', continent: 'Africa', difficulty: 2 },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', continent: 'Africa', difficulty: 2 },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', continent: 'Africa', difficulty: 2 },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', continent: 'Asia', difficulty: 2 },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', continent: 'Asia', difficulty: 2 },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', continent: 'Asia', difficulty: 2 },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', continent: 'Asia', difficulty: 2 },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', continent: 'Europe', difficulty: 2 },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', continent: 'Europe', difficulty: 2 },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', continent: 'Europe', difficulty: 2 },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', continent: 'Europe', difficulty: 2 },

  // Hard flags (difficulty 3)
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', continent: 'Europe', difficulty: 3 },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', continent: 'Europe', difficulty: 3 },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', continent: 'Europe', difficulty: 3 },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', continent: 'Europe', difficulty: 3 },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', continent: 'Europe', difficulty: 3 },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', continent: 'Europe', difficulty: 3 },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', continent: 'Europe', difficulty: 3 },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', continent: 'Europe', difficulty: 3 },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', continent: 'Europe', difficulty: 3 },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', continent: 'Europe', difficulty: 3 },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', continent: 'Europe', difficulty: 3 },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', continent: 'Europe', difficulty: 3 },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', continent: 'Europe', difficulty: 3 },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', continent: 'Europe', difficulty: 3 },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', continent: 'Europe', difficulty: 3 },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', continent: 'Europe', difficulty: 3 },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', continent: 'Asia', difficulty: 3 },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', continent: 'Asia', difficulty: 3 },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', continent: 'Asia', difficulty: 3 },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', continent: 'Asia', difficulty: 3 },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', continent: 'Asia', difficulty: 3 },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', continent: 'Asia', difficulty: 3 },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', continent: 'Asia', difficulty: 3 },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', continent: 'Asia', difficulty: 3 },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', continent: 'Asia', difficulty: 3 },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', continent: 'Asia', difficulty: 3 },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', continent: 'Asia', difficulty: 3 },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', continent: 'Asia', difficulty: 3 },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', continent: 'Asia', difficulty: 3 },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', continent: 'Asia', difficulty: 3 },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', continent: 'Africa', difficulty: 3 },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', continent: 'Africa', difficulty: 3 },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', continent: 'Africa', difficulty: 3 },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', continent: 'Africa', difficulty: 3 },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', continent: 'Africa', difficulty: 3 },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮', continent: 'Africa', difficulty: 3 },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', continent: 'Africa', difficulty: 3 },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', continent: 'Africa', difficulty: 3 },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', continent: 'Africa', difficulty: 3 },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', continent: 'South America', difficulty: 3 },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', continent: 'South America', difficulty: 3 },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', continent: 'South America', difficulty: 3 },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', continent: 'South America', difficulty: 3 },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', continent: 'North America', difficulty: 3 },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', continent: 'North America', difficulty: 3 },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', continent: 'North America', difficulty: 3 },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', continent: 'North America', difficulty: 3 },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', continent: 'North America', difficulty: 3 },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', continent: 'North America', difficulty: 3 },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', continent: 'Oceania', difficulty: 3 },
];

export const CONTINENTS = ['All', 'Africa', 'Asia', 'Europe', 'North America', 'South America', 'Oceania'];
